In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('drug200.csv')

In [3]:
df.sample(5)
df.shape

(200, 6)

In [4]:
X=df.iloc[:,:5]
y=df.iloc[:,5]

In [5]:
X.dtypes

Age              int64
Sex             object
BP              object
Cholesterol     object
Na_to_K        float64
dtype: object

In [6]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [7]:
df['Drug'].unique()

array(['drugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [8]:
X.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [9]:
from sklearn.tree import DecisionTreeClassifier

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [12]:
dt=DecisionTreeClassifier()

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [14]:
ohe=OneHotEncoder(drop='first',sparse = False,dtype=np.int32)
X_train_ohe = ohe.fit_transform(X_train[['Sex']])
X_test_ohe=ohe.transform(X_test[['Sex']])

C:\Users\iitia\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [22]:
from sklearn.preprocessing  import OrdinalEncoder
oe=OrdinalEncoder(categories=[['HIGH','NORMAL','LOW'],['HIGH','NORMAL']])
X_train_oe=oe.fit(X_train[['BP','Cholesterol']])
X_train_oe=oe.transform(X_train[['BP','Cholesterol']])
X_test_oe=oe.transform(X_test[['BP','Cholesterol']])

In [20]:
le = LabelEncoder()

In [21]:
y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)


In [35]:
X_train_age=X_train.drop(columns=['Sex','BP','Cholesterol','Na_to_K']).values
X_test_age=X_test.drop(columns=['Sex','BP','Cholesterol','Na_to_K']).values
X_train_Na_to_K=X_train.drop(columns=['Age','Sex','BP','Cholesterol']).values
X_test_Na_to_K=X_test.drop(columns=['Age','Sex','BP','Cholesterol']).values

In [36]:
X_train_transformed=np.concatenate((X_train_age,X_train_ohe,X_train_oe,X_train_Na_to_K),axis=1)
X_test_transformed=np.concatenate((X_test_age,X_test_ohe,X_test_oe,X_test_Na_to_K),axis=1)

In [37]:
X_test_transformed

array([[65.   ,  1.   ,  0.   ,  1.   , 34.997],
       [49.   ,  0.   ,  1.   ,  1.   ,  9.381],
       [28.   ,  0.   ,  2.   ,  0.   , 19.796],
       [25.   ,  1.   ,  1.   ,  0.   , 19.011],
       [73.   ,  0.   ,  1.   ,  0.   , 19.221],
       [20.   ,  0.   ,  0.   ,  0.   , 11.262],
       [46.   ,  1.   ,  1.   ,  1.   ,  7.285],
       [50.   ,  1.   ,  1.   ,  1.   , 15.79 ],
       [74.   ,  1.   ,  2.   ,  1.   , 11.939],
       [45.   ,  1.   ,  2.   ,  1.   ,  8.37 ],
       [48.   ,  0.   ,  2.   ,  0.   , 15.036],
       [29.   ,  0.   ,  0.   ,  0.   , 29.45 ],
       [59.   ,  1.   ,  0.   ,  0.   , 13.935],
       [42.   ,  1.   ,  0.   ,  1.   , 12.766],
       [59.   ,  0.   ,  2.   ,  0.   , 10.444],
       [47.   ,  1.   ,  2.   ,  1.   , 30.568],
       [57.   ,  1.   ,  2.   ,  1.   , 19.128],
       [35.   ,  1.   ,  1.   ,  1.   ,  7.845],
       [58.   ,  0.   ,  2.   ,  0.   , 26.645],
       [40.   ,  0.   ,  1.   ,  0.   , 10.103],
       [32.   ,  0. 

In [48]:
y_test

array([4, 3, 4, 4, 4, 0, 3, 4, 3, 3, 4, 4, 1, 0, 2, 4, 4, 3, 4, 3, 3, 4,
       3, 1, 1, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 2, 3, 4, 4, 4])

In [39]:
y_train.shape

(160,)

In [40]:
dt.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [41]:
y_pred =dt.predict(X_test_transformed)

In [44]:
from sklearn.metrics import accuracy_score,r2_score

In [45]:
accuracy_score(y_test,y_pred)

1.0

In [46]:
r2_score(y_test,y_pred)

1.0

In [59]:
dt.predict(np.array([49.   ,  0.   ,  1.   ,  1.   ,  9.381]).reshape(1,5))

array([3])